name: CI Pipeline

on:
  push:
    branches: [dev]

  pull_request:
    branches: [dev, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install flake8 black ruff pytest
          pip install --no-cache-dir -r requirements.txt

      - name: Run Linter
        run: ruff check .

      - name: Check Formatting
        run: black --check .

      - name: Run Tests if present
        run: |
          if [ -d "tests" ]; then
            pytest tests --maxfail=1 -v --disable-warnings
          else
            echo "No tests found"
          fi

      - name: Set up  Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build container Image
        run: |
          docker build -t backend_apis:${{ github.sha }} .

      - name: Scan Docker image with Docker Scan
        run: docker scan backend_apis:${{ github.sha }} || true

      - name: Test the container image
        run: |
          docker run -d -p 8000:8000 --name test_container backend_apis:${{ github.sha }}

          echo "Waiting for API..."

          for i in {1..15}; do
            if curl --fail http://0.0.0.0:8000; then
              echo "API is ready"
              break
            fi
            sleep 2
          done

      - name: Check API response
        run: |
          curl --fail http://0.0.0.0:8000/health

      - name: Cleanup container
        run: docker rm -f test_container || true


